<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $perfumes = [
            [
                'name' => 'Velvet Oud',
                'description' => 'A bold, spicy fragrance with woody undertones.',
                'slug' => 'velvet-oud',
                'price' => 79.99,
                'old_price' => 99.99,
                'category' => 'men',
                'image' => 'images/perfumes/velvet-oud.jpg',
            ],
            [
                'name' => 'Rose Éclat',
                'description' => 'Soft floral notes perfect for elegant occasions.',
                'slug' => 'rose-eclat',
                'price' => 59.99,
                'old_price' => 79.99,
                'category' => 'women',
                'image' => 'images/perfumes/rose-eclat.jpg',
            ],
            [
                'name' => 'Noir Intense',
                'description' => 'Dark and sensual with amber and musk.',
                'slug' => 'noir-intense',
                'price' => 85.50,
                'old_price' => 95.00,
                'category' => 'men',
                'image' => 'images/perfumes/noir-intense.jpg',
            ],
            [
                'name' => 'Golden Bloom',
                'description' => 'Citrus top notes with jasmine and vanilla.',
                'slug' => 'golden-bloom',
                'price' => 49.90,
                'old_price' => 69.90,
                'category' => 'women',
                'image' => 'images/perfumes/golden-bloom.jpg',
            ],
            [
                'name' => 'Aqua Legend',
                'description' => 'Fresh aquatic scent with hints of bergamot.',
                'slug' => 'aqua-legend',
                'price' => 64.00,
                'old_price' => null,
                'category' => 'men',
                'image' => 'images/perfumes/aqua-legend.jpg',
            ],
            [
                'name' => 'Luna Rosa',
                'description' => 'Soft floral perfume with rose and white musk.',
                'slug' => 'luna-rosa',
                'price' => 72.00,
                'old_price' => 82.00,
                'category' => 'women',
                'image' => 'images/perfumes/luna-rosa.jpg',
            ],
            [
                'name' => 'Urban Spice',
                'description' => 'Bold spices and smoky undertones.',
                'slug' => 'urban-spice',
                'price' => 54.00,
                'old_price' => null,
                'category' => 'men',
                'image' => 'images/perfumes/urban-spice.jpg',
            ],
            [
                'name' => 'Pink Mirage',
                'description' => 'Fruity and floral for a fresh daily scent.',
                'slug' => 'pink-mirage',
                'price' => 39.99,
                'old_price' => 59.99,
                'category' => 'women',
                'image' => 'images/perfumes/pink-mirage.jpg',
            ],
            [
                'name' => 'Night Fury',
                'description' => 'A mysterious blend of leather and oud.',
                'slug' => 'night-fury',
                'price' => 89.00,
                'old_price' => 109.00,
                'category' => 'men',
                'image' => 'images/perfumes/night-fury.jpg',
            ],
            [
                'name' => 'Blush Petals',
                'description' => 'Delicate petals with sweet pear notes.',
                'slug' => 'blush-petals',
                'price' => 45.00,
                'old_price' => 60.00,
                'category' => 'women',
                'image' => 'images/perfumes/blush-petals.jpg',
            ],
            [
                'name' => 'Cedar Trail',
                'description' => 'Earthy and rugged with cedarwood and sandalwood.',
                'slug' => 'cedar-trail',
                'price' => 68.75,
                'old_price' => null,
                'category' => 'men',
                'image' => 'images/perfumes/cedar-trail.jpg',
            ],
            [
                'name' => 'Vanilla Orchid',
                'description' => 'Warm vanilla and light orchid bouquet.',
                'slug' => 'vanilla-orchid',
                'price' => 55.50,
                'old_price' => 70.00,
                'category' => 'women',
                'image' => 'images/perfumes/vanilla-orchid.jpg',
            ],
            [
                'name' => 'Royal Musk',
                'description' => 'Classic musk with a touch of citrus.',
                'slug' => 'royal-musk',
                'price' => 77.00,
                'old_price' => 95.00,
                'category' => 'men',
                'image' => 'images/perfumes/royal-musk.jpg',
            ],
            [
                'name' => 'Amber Bloom',
                'description' => 'Amber and floral fusion with a warm finish.',
                'slug' => 'amber-bloom',
                'price' => 69.00,
                'old_price' => null,
                'category' => 'women',
                'image' => 'images/perfumes/amber-bloom.jpg',
            ],
            [
                'name' => 'Iron Flame',
                'description' => 'Metallic, cool, and smoky aroma.',
                'slug' => 'iron-flame',
                'price' => 73.90,
                'old_price' => 89.90,
                'category' => 'men',
                'image' => 'images/perfumes/iron-flame.jpg',
            ],
            [
                'name' => 'Jasmine Soul',
                'description' => 'Heart of jasmine with soft undertones.',
                'slug' => 'jasmine-soul',
                'price' => 42.50,
                'old_price' => 52.50,
                'category' => 'women',
                'image' => 'images/perfumes/jasmine-soul.jpg',
            ],
            [
                'name' => 'Wild Tobacco',
                'description' => 'Masculine blend of tobacco leaf and patchouli.',
                'slug' => 'wild-tobacco',
                'price' => 59.99,
                'old_price' => null,
                'category' => 'men',
                'image' => 'images/perfumes/wild-tobacco.jpg',
            ],
            [
                'name' => 'Cherry Bloom',
                'description' => 'Cherry blossoms and soft vanilla.',
                'slug' => 'cherry-bloom',
                'price' => 39.00,
                'old_price' => 49.00,
                'category' => 'women',
                'image' => 'images/perfumes/cherry-bloom.jpg',
            ],
            [
                'name' => 'Ocean Drift',
                'description' => 'Clean sea breeze with marine layers.',
                'slug' => 'ocean-drift',
                'price' => 61.00,
                'old_price' => 71.00,
                'category' => 'men',
                'image' => 'images/perfumes/ocean-drift.jpg',
            ],
            [
                'name' => 'Golden Rose',
                'description' => 'Elegant rose and golden musk.',
                'slug' => 'golden-rose',
                'price' => 58.00,
                'old_price' => null,
                'category' => 'women',
                'image' => 'images/perfumes/golden-rose.jpg',
            ],
            [
                'name' => 'Arctic Ice',
                'description' => 'Cool mint and sharp citrus notes.',
                'slug' => 'arctic-ice',
                'price' => 66.60,
                'old_price' => 80.00,
                'category' => 'men',
                'image' => 'images/perfumes/arctic-ice.jpg',
            ],
            [
                'name' => 'Floral Dusk',
                'description' => 'Evening fragrance with peony and musk.',
                'slug' => 'floral-dusk',
                'price' => 47.75,
                'old_price' => null,
                'category' => 'women',
                'image' => 'images/perfumes/floral-dusk.jpg',
            ],
            [
                'name' => 'Iron Black',
                'description' => 'A powerful masculine scent for all-day wear.',
                'slug' => 'iron-black',
                'price' => 83.00,
                'old_price' => 99.00,
                'category' => 'men',
                'image' => 'images/perfumes/iron-black.jpg',
            ],
            [
                'name' => 'Peach Muse',
                'description' => 'Juicy peach and fresh mandarin.',
                'slug' => 'peach-muse',
                'price' => 43.00,
                'old_price' => 50.00,
                'category' => 'women',
                'image' => 'images/perfumes/peach-muse.jpg',
            ],
            [
                'name' => 'Mystic Sandal',
                'description' => 'Sandalwood richness for calming vibes.',
                'slug' => 'mystic-sandal',
                'price' => 71.25,
                'old_price' => null,
                'category' => 'men',
                'image' => 'images/perfumes/mystic-sandal.jpg',
            ],
            [
                'name' => 'Lilac Rain',
                'description' => 'Fresh lilac and cool rain notes.',
                'slug' => 'lilac-rain',
                'price' => 53.00,
                'old_price' => 63.00,
                'category' => 'women',
                'image' => 'images/perfumes/lilac-rain.jpg',
            ],
            [
                'name' => 'Citrus Edge',
                'description' => 'Zesty lime and bold spices.',
                'slug' => 'citrus-edge',
                'price' => 67.40,
                'old_price' => 77.00,
                'category' => 'men',
                'image' => 'images/perfumes/citrus-edge.jpg',
            ],
            [
                'name' => 'Moon Dust',
                'description' => 'Mystical floral top notes with a powdery base.',
                'slug' => 'moon-dust',
                'price' => 44.44,
                'old_price' => null,
                'category' => 'women',
                'image' => 'images/perfumes/moon-dust.jpg',
            ],
            [
                'name' => 'Blackwood',
                'description' => 'A dark, woody experience with cinnamon.',
                'slug' => 'blackwood',
                'price' => 74.99,
                'old_price' => 89.99,
                'category' => 'men',
                'image' => 'images/perfumes/blackwood.jpg',
            ],
        ];
        foreach ($perfumes as $perfume) {
            Product::create($perfume);
        }        
    }
}
